### ISSUE TITLE
volumeMount policy

### ISSUE THREAD

**Issue by viccuad** [kubewarden/volumeMounts-policy#3]
## volumemounts-policy

Policy that inspects containers, init containers, and ephemeral containers, and
restricts their usage of volumes by  checking the `volume` name being used in
`volumeMounts[*].name`.

The policy can either target `Pods`, or [workload
resources](https://kubernetes.io/docs/concepts/workloads/) (`Deployments`,
`ReplicaSets`, `DaemonSets`, `ReplicationControllers`, `Jobs`, `CronJobs`) by
setting the policy's `spec.rules` accordingly.

Both have trade-offs:
* Policy targets Pods: Different kind of resources (be them native or CRDs) can
  create Pods. By having the policy target Pods, we guarantee that all the Pods
  are going to be compliant, even those created from CRDs.
  However, this could lead to confusion among users, as high level Kubernetes
  resources would be successfully created, but they would stay in a non
  reconciled state. Example: a Deployment creating a non-compliant Pod would be
  created, but it would never have all its replicas running.
* Policy targets workload resources (e.g: Deployment): the policy inspect higher
  order resource (e.g. Deployment): users will get immediate feedback about
  rejections.
  However, non compliant pods created by another high level resource (be it
  native to Kubernetes, or a CRD), may not get rejected.

## Settings
```yaml
behaviour: denylist # one of denylist (default), allowlist
operator: AnyIn # one of AllIn, AnyIn (default), AllNotIn, AnyNotIn
volumeMountNames:  # list of volumeMounts.name to match using the defined operator
  - foo
  - bar
  - baz
```

- `AllIn` checks if all of the volumeMountNames are in the Pod
- `AnyIn` checks if any of the volumeMountNames are in the Pod
- `AllNotIn` checks if all of the volumeMountNames are not in the Pod
- `AnyNotIn` checks if any of the volumeMountNames are not in the Pod

## Examples

```yaml
# reject volumeMounts named `my-test-volume` or  `my-test2-volume`
behaviour: denylist
operator: AnyIn
volumeMountsNames:
  - my-test-volume
  - my-test2-volume
```

```yaml
# only allow volumeMounts named `my-test3-volume`
behaviour: allowlist
operator: AnyIn
volumeMounts:
  - my-test3-volume
```

```yaml
# container cannot use both volumes at once, only one or the other
behaviour: denylist
operator: AllIn
volumeMounts:
  - my-test1-volume
  - my-test2-volume
```
